AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        MyTimeApi1:
          Type: Api
          Properties:
            Path: /TimeResource1
            Method: GET
  QueryParamFunctionGR:
    Type: AWS::Serverless::Function
    Properties:
      Handler: query-param.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        QueryParamApiGR:
          Type: Api
          Properties:
            Path: /Greeting
            Method: GET
